# conda env create -f agat_environment.yml
name: agat
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - perl-bioperl
  - perl-clone
  - perl-moose
  - perl-graph
  - perl-lwp-simple
  - perl-statistics-r
  - perl-json
  - perl-sort-naturally
  - perl-data-dumper
