# conda env create -f conda_environment_AGAT.yml
name: agat
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - perl >=5.8
  - perl-bioperl >=1.7.8
  - perl-carp
  - perl-clone
  - perl-extutils-makemaker
  - perl-file-chdir
  - perl-file-temp
  - perl-file-share
  - perl-file-sharedir-install
  - perl-graph
  - perl-list-moreutils
  - perl-lwp-simple >=6.39
  - perl-lwp-protocol-https
  - perl-parallel-forkmanager 
  - perl-sort-naturally
  - perl-storable
  - perl-term-progressbar
  - perl-moose
  - perl-yaml
  - libdb
