# conda env create -f conda_environment_AGAT.yml
name: agat
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - perl
  - perl-bioperl
  - perl-clone
  - perl-graph
  - perl-lwp-simple
  - perl-statistics-r
  - perl-json
  - perl-carp
  - perl-sort-naturally
  - perl-file-share
  - perl-file-sharedir-install
  - perl-moose
  - r-base
  - libdb
