---
check_all_level1_locations: false
check_all_level2_locations: false
check_all_level3_locations: false
check_cds: false
check_exons: false
check_identical_isoforms: false
check_l1_linked_to_l2: false
check_l2_linked_to_l3: false
check_sequential: false
check_utrs: false
clean_attributes_from_template: true
cpu: 2
create_l3_for_l2_orphan: false
debug: true
force_gff_input_version: 3
gff_output_version: 2
gtf_output_version: 2
locus_tag:
  - test1
  - test2
log: false
merge_loci: true
output_format: gtf
prefix_new_id: nbisTEST
progress_bar: false
remove_orphan_l1: false
tabix: false
throw_fasta: true
verbose: 3
